[tool.ruff]
target-version = "py38" # minimum supported version
line-length = 90

[tool.ruff.lint]
select = [
    "C9",
    "D1",
    "E",
    "F",
    "I",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = ["D1"]

[tool.ruff.lint.isort]
known-first-party = ["stac_fastapi"]
known-third-party = ["stac_pydantic", "fastapi"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.format]
quote-style = "double"
